language: node_js
node_js:
  - "0.12"
#addons:
#  sauce_connect: true
env:
  global:
    - secure: bttItzE5WWQLDj/WBAYVrjHYE+AZMPvCwKrkk0RmBrC+cplU0jGMTlCQo/arbnzkKW5VUU9joND0azOIUqstNYwVR4rwgrZ/d6ejQvfasV6WiUkmx7ZSWSM4dmmN4exK2zcVkNsSHDGhsKx6RdJ8QDAXu134UOCb3lvmxZlIR7Y=
    - secure: Zb+xVV0qwJgEhm5/QwQojyPIkSctKwnzCh7zRj9T0OAt9eO4YaxRv+D2aeIjzXGQVwmYCJrOYHFjZfVqkwx9ItNCMqJepvCI9loir8lt8/eBryMpNjjNVGT3q39XqUAHKrLD7rw349QX1Z2Zwr9qyUtyedEn+H3oH/cc8uVbOv8=